server:
  port: 7878
spring:

  datasource:
    username: root
    password: wsdyw123
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  jackson:
    serialization:
      fail-on-empty-beans: false
  boot:
    admin:
      notify:
        pagerduty:
          client-url: localhost:7879
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always




